nohup: ignoring input
[2025-10-21 21:03:19 +0000] [28224] [INFO] Starting gunicorn 23.0.0
[2025-10-21 21:03:19 +0000] [28224] [INFO] Listening at: http://0.0.0.0:8080 (28224)
[2025-10-21 21:03:19 +0000] [28224] [INFO] Using worker: sync
[2025-10-21 21:03:19 +0000] [28225] [INFO] Booting worker with pid: 28225
[2025-10-21 21:03:19 +0000] [28225] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/home/jules/anaconda3/envs/editing/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2025-10-21 21:03:19 +0000] [28225] [INFO] Worker exiting (pid: 28225)
[2025-10-21 21:03:19 +0000] [28224] [ERROR] Worker (pid:28225) exited with code 3
[2025-10-21 21:03:19 +0000] [28224] [ERROR] Shutting down: Master
[2025-10-21 21:03:19 +0000] [28224] [ERROR] Reason: Worker failed to boot.
